name: Release

on:
  push:
    tags: [ 'v*' ]

permissions:
  contents: write

jobs:
  # Build using the reusable workflow
  build:
    name: Build Release Binaries
    uses: ./.github/workflows/build.yml
    with:
      upload_artifacts: true
      artifact_retention_days: 90  # Keep release builds longer
      build_profile: 'release'

  # Create GitHub Release
  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts/
        
    - name: Display structure of downloaded files
      run: |
        echo "Downloaded artifacts:"
        find artifacts/ -type f -exec ls -la {} \;

    - name: Prepare release assets
      run: |
        mkdir -p release-assets
        
        # Move all binaries and checksums to release-assets directory
        find artifacts/ -name "hielo-*" -type f -exec cp {} release-assets/ \;
        find artifacts/ -name "*.sha256" -type f -exec cp {} release-assets/ \;
        
        # Create a combined checksum file
        cd release-assets
        cat *.sha256 > checksums.txt
        
        echo "Release assets prepared:"
        ls -la

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.ref_name }}
        name: Release ${{ github.ref_name }}
        draft: false
        prerelease: ${{ contains(github.ref_name, '-') }}
        generate_release_notes: true
        files: |
          release-assets/hielo-*
          release-assets/checksums.txt
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
